// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_grpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yolo_5fgrpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yolo_5fgrpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yolo_5fgrpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yolo_5fgrpc_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yolo_5fgrpc_2eproto;
namespace yolo_grpc {
class CamInfo;
class CamInfoDefaultTypeInternal;
extern CamInfoDefaultTypeInternal _CamInfo_default_instance_;
class Detection;
class DetectionDefaultTypeInternal;
extern DetectionDefaultTypeInternal _Detection_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class TrackPoint;
class TrackPointDefaultTypeInternal;
extern TrackPointDefaultTypeInternal _TrackPoint_default_instance_;
}  // namespace yolo_grpc
PROTOBUF_NAMESPACE_OPEN
template<> ::yolo_grpc::CamInfo* Arena::CreateMaybeMessage<::yolo_grpc::CamInfo>(Arena*);
template<> ::yolo_grpc::Detection* Arena::CreateMaybeMessage<::yolo_grpc::Detection>(Arena*);
template<> ::yolo_grpc::Response* Arena::CreateMaybeMessage<::yolo_grpc::Response>(Arena*);
template<> ::yolo_grpc::TrackPoint* Arena::CreateMaybeMessage<::yolo_grpc::TrackPoint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yolo_grpc {

// ===================================================================

class CamInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.CamInfo) */ {
 public:
  CamInfo();
  virtual ~CamInfo();

  CamInfo(const CamInfo& from);
  CamInfo(CamInfo&& from) noexcept
    : CamInfo() {
    *this = ::std::move(from);
  }

  inline CamInfo& operator=(const CamInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CamInfo& operator=(CamInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CamInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CamInfo* internal_default_instance() {
    return reinterpret_cast<const CamInfo*>(
               &_CamInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CamInfo& a, CamInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(CamInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CamInfo* New() const final {
    return CreateMaybeMessage<CamInfo>(nullptr);
  }

  CamInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CamInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CamInfo& from);
  void MergeFrom(const CamInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CamInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.CamInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrackFieldNumber = 5,
    kCamIdFieldNumber = 1,
    kImageFieldNumber = 3,
    kDetectionFieldNumber = 4,
    kTimestampFieldNumber = 2,
  };
  // repeated .yolo_grpc.TrackPoint track = 5;
  int track_size() const;
  private:
  int _internal_track_size() const;
  public:
  void clear_track();
  ::yolo_grpc::TrackPoint* mutable_track(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::TrackPoint >*
      mutable_track();
  private:
  const ::yolo_grpc::TrackPoint& _internal_track(int index) const;
  ::yolo_grpc::TrackPoint* _internal_add_track();
  public:
  const ::yolo_grpc::TrackPoint& track(int index) const;
  ::yolo_grpc::TrackPoint* add_track();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::TrackPoint >&
      track() const;

  // string cam_id = 1;
  void clear_cam_id();
  const std::string& cam_id() const;
  void set_cam_id(const std::string& value);
  void set_cam_id(std::string&& value);
  void set_cam_id(const char* value);
  void set_cam_id(const char* value, size_t size);
  std::string* mutable_cam_id();
  std::string* release_cam_id();
  void set_allocated_cam_id(std::string* cam_id);
  private:
  const std::string& _internal_cam_id() const;
  void _internal_set_cam_id(const std::string& value);
  std::string* _internal_mutable_cam_id();
  public:

  // bytes image = 3;
  void clear_image();
  const std::string& image() const;
  void set_image(const std::string& value);
  void set_image(std::string&& value);
  void set_image(const char* value);
  void set_image(const void* value, size_t size);
  std::string* mutable_image();
  std::string* release_image();
  void set_allocated_image(std::string* image);
  private:
  const std::string& _internal_image() const;
  void _internal_set_image(const std::string& value);
  std::string* _internal_mutable_image();
  public:

  // .yolo_grpc.Detection detection = 4;
  bool has_detection() const;
  private:
  bool _internal_has_detection() const;
  public:
  void clear_detection();
  const ::yolo_grpc::Detection& detection() const;
  ::yolo_grpc::Detection* release_detection();
  ::yolo_grpc::Detection* mutable_detection();
  void set_allocated_detection(::yolo_grpc::Detection* detection);
  private:
  const ::yolo_grpc::Detection& _internal_detection() const;
  ::yolo_grpc::Detection* _internal_mutable_detection();
  public:

  // int64 timestamp = 2;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.CamInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::TrackPoint > track_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cam_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_;
  ::yolo_grpc::Detection* detection_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class Detection :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.Detection) */ {
 public:
  Detection();
  virtual ~Detection();

  Detection(const Detection& from);
  Detection(Detection&& from) noexcept
    : Detection() {
    *this = ::std::move(from);
  }

  inline Detection& operator=(const Detection& from) {
    CopyFrom(from);
    return *this;
  }
  inline Detection& operator=(Detection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Detection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Detection* internal_default_instance() {
    return reinterpret_cast<const Detection*>(
               &_Detection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Detection& a, Detection& b) {
    a.Swap(&b);
  }
  inline void Swap(Detection* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Detection* New() const final {
    return CreateMaybeMessage<Detection>(nullptr);
  }

  Detection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Detection>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Detection& from);
  void MergeFrom(const Detection& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Detection* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.Detection";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLineIdFieldNumber = 5,
    kXLeftFieldNumber = 1,
    kYTopFieldNumber = 2,
    kHeightFieldNumber = 3,
    kWidthFieldNumber = 4,
  };
  // string line_id = 5;
  void clear_line_id();
  const std::string& line_id() const;
  void set_line_id(const std::string& value);
  void set_line_id(std::string&& value);
  void set_line_id(const char* value);
  void set_line_id(const char* value, size_t size);
  std::string* mutable_line_id();
  std::string* release_line_id();
  void set_allocated_line_id(std::string* line_id);
  private:
  const std::string& _internal_line_id() const;
  void _internal_set_line_id(const std::string& value);
  std::string* _internal_mutable_line_id();
  public:

  // int32 x_left = 1;
  void clear_x_left();
  ::PROTOBUF_NAMESPACE_ID::int32 x_left() const;
  void set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x_left() const;
  void _internal_set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y_top = 2;
  void clear_y_top();
  ::PROTOBUF_NAMESPACE_ID::int32 y_top() const;
  void set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y_top() const;
  void _internal_set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 height = 3;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::int32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 width = 4;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::int32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.Detection)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr line_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_left_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_top_;
  ::PROTOBUF_NAMESPACE_ID::int32 height_;
  ::PROTOBUF_NAMESPACE_ID::int32 width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class TrackPoint :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.TrackPoint) */ {
 public:
  TrackPoint();
  virtual ~TrackPoint();

  TrackPoint(const TrackPoint& from);
  TrackPoint(TrackPoint&& from) noexcept
    : TrackPoint() {
    *this = ::std::move(from);
  }

  inline TrackPoint& operator=(const TrackPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackPoint& operator=(TrackPoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TrackPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrackPoint* internal_default_instance() {
    return reinterpret_cast<const TrackPoint*>(
               &_TrackPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TrackPoint& a, TrackPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(TrackPoint* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrackPoint* New() const final {
    return CreateMaybeMessage<TrackPoint>(nullptr);
  }

  TrackPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrackPoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TrackPoint& from);
  void MergeFrom(const TrackPoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrackPoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.TrackPoint";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::int32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y = 2;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::int32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y() const;
  void _internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.TrackPoint)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class Response :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.Response";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
    kWarningFieldNumber = 2,
    kErrorFieldNumber = 3,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string warning = 2;
  void clear_warning();
  const std::string& warning() const;
  void set_warning(const std::string& value);
  void set_warning(std::string&& value);
  void set_warning(const char* value);
  void set_warning(const char* value, size_t size);
  std::string* mutable_warning();
  std::string* release_warning();
  void set_allocated_warning(std::string* warning);
  private:
  const std::string& _internal_warning() const;
  void _internal_set_warning(const std::string& value);
  std::string* _internal_mutable_warning();
  public:

  // string error = 3;
  void clear_error();
  const std::string& error() const;
  void set_error(const std::string& value);
  void set_error(std::string&& value);
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  std::string* mutable_error();
  std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.Response)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr warning_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CamInfo

// string cam_id = 1;
inline void CamInfo::clear_cam_id() {
  cam_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CamInfo::cam_id() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.cam_id)
  return _internal_cam_id();
}
inline void CamInfo::set_cam_id(const std::string& value) {
  _internal_set_cam_id(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.CamInfo.cam_id)
}
inline std::string* CamInfo::mutable_cam_id() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.cam_id)
  return _internal_mutable_cam_id();
}
inline const std::string& CamInfo::_internal_cam_id() const {
  return cam_id_.GetNoArena();
}
inline void CamInfo::_internal_set_cam_id(const std::string& value) {
  
  cam_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CamInfo::set_cam_id(std::string&& value) {
  
  cam_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.CamInfo.cam_id)
}
inline void CamInfo::set_cam_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cam_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.CamInfo.cam_id)
}
inline void CamInfo::set_cam_id(const char* value, size_t size) {
  
  cam_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.CamInfo.cam_id)
}
inline std::string* CamInfo::_internal_mutable_cam_id() {
  
  return cam_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CamInfo::release_cam_id() {
  // @@protoc_insertion_point(field_release:yolo_grpc.CamInfo.cam_id)
  
  return cam_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CamInfo::set_allocated_cam_id(std::string* cam_id) {
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cam_id);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.CamInfo.cam_id)
}

// int64 timestamp = 2;
inline void CamInfo::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CamInfo::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CamInfo::timestamp() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.timestamp)
  return _internal_timestamp();
}
inline void CamInfo::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void CamInfo::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.CamInfo.timestamp)
}

// bytes image = 3;
inline void CamInfo::clear_image() {
  image_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CamInfo::image() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.image)
  return _internal_image();
}
inline void CamInfo::set_image(const std::string& value) {
  _internal_set_image(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.CamInfo.image)
}
inline std::string* CamInfo::mutable_image() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.image)
  return _internal_mutable_image();
}
inline const std::string& CamInfo::_internal_image() const {
  return image_.GetNoArena();
}
inline void CamInfo::_internal_set_image(const std::string& value) {
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CamInfo::set_image(std::string&& value) {
  
  image_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.CamInfo.image)
}
inline void CamInfo::set_image(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.CamInfo.image)
}
inline void CamInfo::set_image(const void* value, size_t size) {
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.CamInfo.image)
}
inline std::string* CamInfo::_internal_mutable_image() {
  
  return image_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CamInfo::release_image() {
  // @@protoc_insertion_point(field_release:yolo_grpc.CamInfo.image)
  
  return image_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CamInfo::set_allocated_image(std::string* image) {
  if (image != nullptr) {
    
  } else {
    
  }
  image_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.CamInfo.image)
}

// .yolo_grpc.Detection detection = 4;
inline bool CamInfo::_internal_has_detection() const {
  return this != internal_default_instance() && detection_ != nullptr;
}
inline bool CamInfo::has_detection() const {
  return _internal_has_detection();
}
inline void CamInfo::clear_detection() {
  if (GetArenaNoVirtual() == nullptr && detection_ != nullptr) {
    delete detection_;
  }
  detection_ = nullptr;
}
inline const ::yolo_grpc::Detection& CamInfo::_internal_detection() const {
  const ::yolo_grpc::Detection* p = detection_;
  return p != nullptr ? *p : *reinterpret_cast<const ::yolo_grpc::Detection*>(
      &::yolo_grpc::_Detection_default_instance_);
}
inline const ::yolo_grpc::Detection& CamInfo::detection() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.detection)
  return _internal_detection();
}
inline ::yolo_grpc::Detection* CamInfo::release_detection() {
  // @@protoc_insertion_point(field_release:yolo_grpc.CamInfo.detection)
  
  ::yolo_grpc::Detection* temp = detection_;
  detection_ = nullptr;
  return temp;
}
inline ::yolo_grpc::Detection* CamInfo::_internal_mutable_detection() {
  
  if (detection_ == nullptr) {
    auto* p = CreateMaybeMessage<::yolo_grpc::Detection>(GetArenaNoVirtual());
    detection_ = p;
  }
  return detection_;
}
inline ::yolo_grpc::Detection* CamInfo::mutable_detection() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.detection)
  return _internal_mutable_detection();
}
inline void CamInfo::set_allocated_detection(::yolo_grpc::Detection* detection) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete detection_;
  }
  if (detection) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      detection = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, detection, submessage_arena);
    }
    
  } else {
    
  }
  detection_ = detection;
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.CamInfo.detection)
}

// repeated .yolo_grpc.TrackPoint track = 5;
inline int CamInfo::_internal_track_size() const {
  return track_.size();
}
inline int CamInfo::track_size() const {
  return _internal_track_size();
}
inline void CamInfo::clear_track() {
  track_.Clear();
}
inline ::yolo_grpc::TrackPoint* CamInfo::mutable_track(int index) {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.track)
  return track_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::TrackPoint >*
CamInfo::mutable_track() {
  // @@protoc_insertion_point(field_mutable_list:yolo_grpc.CamInfo.track)
  return &track_;
}
inline const ::yolo_grpc::TrackPoint& CamInfo::_internal_track(int index) const {
  return track_.Get(index);
}
inline const ::yolo_grpc::TrackPoint& CamInfo::track(int index) const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.track)
  return _internal_track(index);
}
inline ::yolo_grpc::TrackPoint* CamInfo::_internal_add_track() {
  return track_.Add();
}
inline ::yolo_grpc::TrackPoint* CamInfo::add_track() {
  // @@protoc_insertion_point(field_add:yolo_grpc.CamInfo.track)
  return _internal_add_track();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::TrackPoint >&
CamInfo::track() const {
  // @@protoc_insertion_point(field_list:yolo_grpc.CamInfo.track)
  return track_;
}

// -------------------------------------------------------------------

// Detection

// int32 x_left = 1;
inline void Detection::clear_x_left() {
  x_left_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_x_left() const {
  return x_left_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::x_left() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.x_left)
  return _internal_x_left();
}
inline void Detection::_internal_set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_left_ = value;
}
inline void Detection::set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x_left(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.x_left)
}

// int32 y_top = 2;
inline void Detection::clear_y_top() {
  y_top_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_y_top() const {
  return y_top_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::y_top() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.y_top)
  return _internal_y_top();
}
inline void Detection::_internal_set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_top_ = value;
}
inline void Detection::set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y_top(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.y_top)
}

// int32 height = 3;
inline void Detection::clear_height() {
  height_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::height() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.height)
  return _internal_height();
}
inline void Detection::_internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  height_ = value;
}
inline void Detection::set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.height)
}

// int32 width = 4;
inline void Detection::clear_width() {
  width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::width() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.width)
  return _internal_width();
}
inline void Detection::_internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  width_ = value;
}
inline void Detection::set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.width)
}

// string line_id = 5;
inline void Detection::clear_line_id() {
  line_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Detection::line_id() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.line_id)
  return _internal_line_id();
}
inline void Detection::set_line_id(const std::string& value) {
  _internal_set_line_id(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.line_id)
}
inline std::string* Detection::mutable_line_id() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Detection.line_id)
  return _internal_mutable_line_id();
}
inline const std::string& Detection::_internal_line_id() const {
  return line_id_.GetNoArena();
}
inline void Detection::_internal_set_line_id(const std::string& value) {
  
  line_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Detection::set_line_id(std::string&& value) {
  
  line_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Detection.line_id)
}
inline void Detection::set_line_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  line_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Detection.line_id)
}
inline void Detection::set_line_id(const char* value, size_t size) {
  
  line_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Detection.line_id)
}
inline std::string* Detection::_internal_mutable_line_id() {
  
  return line_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Detection::release_line_id() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Detection.line_id)
  
  return line_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Detection::set_allocated_line_id(std::string* line_id) {
  if (line_id != nullptr) {
    
  } else {
    
  }
  line_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), line_id);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Detection.line_id)
}

// -------------------------------------------------------------------

// TrackPoint

// int32 x = 1;
inline void TrackPoint::clear_x() {
  x_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TrackPoint::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TrackPoint::x() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.TrackPoint.x)
  return _internal_x();
}
inline void TrackPoint::_internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_ = value;
}
inline void TrackPoint::set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.TrackPoint.x)
}

// int32 y = 2;
inline void TrackPoint::clear_y() {
  y_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TrackPoint::_internal_y() const {
  return y_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TrackPoint::y() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.TrackPoint.y)
  return _internal_y();
}
inline void TrackPoint::_internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_ = value;
}
inline void TrackPoint::set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.TrackPoint.y)
}

// -------------------------------------------------------------------

// Response

// string message = 1;
inline void Response::clear_message() {
  message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::message() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Response.message)
  return _internal_message();
}
inline void Response::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Response.message)
}
inline std::string* Response::mutable_message() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Response.message)
  return _internal_mutable_message();
}
inline const std::string& Response::_internal_message() const {
  return message_.GetNoArena();
}
inline void Response::_internal_set_message(const std::string& value) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response::set_message(std::string&& value) {
  
  message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Response.message)
}
inline void Response::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Response.message)
}
inline void Response::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Response.message)
}
inline std::string* Response::_internal_mutable_message() {
  
  return message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_message() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Response.message)
  
  return message_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Response.message)
}

// string warning = 2;
inline void Response::clear_warning() {
  warning_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::warning() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Response.warning)
  return _internal_warning();
}
inline void Response::set_warning(const std::string& value) {
  _internal_set_warning(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Response.warning)
}
inline std::string* Response::mutable_warning() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Response.warning)
  return _internal_mutable_warning();
}
inline const std::string& Response::_internal_warning() const {
  return warning_.GetNoArena();
}
inline void Response::_internal_set_warning(const std::string& value) {
  
  warning_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response::set_warning(std::string&& value) {
  
  warning_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Response.warning)
}
inline void Response::set_warning(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  warning_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Response.warning)
}
inline void Response::set_warning(const char* value, size_t size) {
  
  warning_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Response.warning)
}
inline std::string* Response::_internal_mutable_warning() {
  
  return warning_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_warning() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Response.warning)
  
  return warning_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_warning(std::string* warning) {
  if (warning != nullptr) {
    
  } else {
    
  }
  warning_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), warning);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Response.warning)
}

// string error = 3;
inline void Response::clear_error() {
  error_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::error() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Response.error)
  return _internal_error();
}
inline void Response::set_error(const std::string& value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Response.error)
}
inline std::string* Response::mutable_error() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Response.error)
  return _internal_mutable_error();
}
inline const std::string& Response::_internal_error() const {
  return error_.GetNoArena();
}
inline void Response::_internal_set_error(const std::string& value) {
  
  error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response::set_error(std::string&& value) {
  
  error_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Response.error)
}
inline void Response::set_error(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Response.error)
}
inline void Response::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Response.error)
}
inline std::string* Response::_internal_mutable_error() {
  
  return error_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_error() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Response.error)
  
  return error_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Response.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace yolo_grpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yolo_5fgrpc_2eproto
