[net]
cfg="./yolov3.cfg" # path to yolo config
weights="./yolov3.weights" # path to yolo weights
confThreshold = 0.5 # confidence treshold
nmsThreshold = 0.4 # non max supression treshold
inpWidth = 416 
inpHeight = 416

[input]
camera_id=0 
video="./data/video_example.mpg" # if exists video file would be processed

[tracker]
distTreshold = 200 # Distance treshold 
histTreshold = 0.6 # Hist treshold
pointsInTrack = 50 # number of points to store in track
maxNoMatch = 15 # track lifetime(frames) without finding the next prediction

# @TODO:[lines] represents detection lines
