[net]
cfg="./yolov3.cfg" # path to yolo config
weights="./yolov3.weights" # path to yolo weights
confThreshold = 0.5 # confidence treshold
nmsThreshold = 0.4 # non max supression treshold
inpWidth = 416 
inpHeight = 416

[input]
camera_id=0 
video="./data/video_example.mpg" # if exists video file would be processed

[tracker]
distTreshold = 200 # Distance treshold 
histTreshold = 0.6 # Hist treshold
pointsInTrack = 10 # number of points to store in track
maxNoMatch = 5 # track lifetime(frames) without finding the next prediction
detectClasses = [0,1,2,3,4]
lines = [
    #{id =0, beg = [100, 100], end = [500, 500]},
    {id=1, beg = [300, 700], end = [1700, 700]} 
]