// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yolo_grpc.proto

#include "yolo_grpc.pb.h"
#include "yolo_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace yolo_grpc {

static const char* STYolo_method_names[] = {
  "/yolo_grpc.STYolo/EndDetection",
};

std::unique_ptr< STYolo::Stub> STYolo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< STYolo::Stub> stub(new STYolo::Stub(channel));
  return stub;
}

STYolo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_EndDetection_(STYolo_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status STYolo::Stub::EndDetection(::grpc::ClientContext* context, const ::yolo_grpc::CamInfo& request, ::yolo_grpc::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_EndDetection_, context, request, response);
}

void STYolo::Stub::experimental_async::EndDetection(::grpc::ClientContext* context, const ::yolo_grpc::CamInfo* request, ::yolo_grpc::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_EndDetection_, context, request, response, std::move(f));
}

void STYolo::Stub::experimental_async::EndDetection(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::yolo_grpc::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_EndDetection_, context, request, response, std::move(f));
}

void STYolo::Stub::experimental_async::EndDetection(::grpc::ClientContext* context, const ::yolo_grpc::CamInfo* request, ::yolo_grpc::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_EndDetection_, context, request, response, reactor);
}

void STYolo::Stub::experimental_async::EndDetection(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::yolo_grpc::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_EndDetection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::yolo_grpc::Response>* STYolo::Stub::AsyncEndDetectionRaw(::grpc::ClientContext* context, const ::yolo_grpc::CamInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::yolo_grpc::Response>::Create(channel_.get(), cq, rpcmethod_EndDetection_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::yolo_grpc::Response>* STYolo::Stub::PrepareAsyncEndDetectionRaw(::grpc::ClientContext* context, const ::yolo_grpc::CamInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::yolo_grpc::Response>::Create(channel_.get(), cq, rpcmethod_EndDetection_, context, request, false);
}

STYolo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      STYolo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< STYolo::Service, ::yolo_grpc::CamInfo, ::yolo_grpc::Response>(
          std::mem_fn(&STYolo::Service::EndDetection), this)));
}

STYolo::Service::~Service() {
}

::grpc::Status STYolo::Service::EndDetection(::grpc::ServerContext* context, const ::yolo_grpc::CamInfo* request, ::yolo_grpc::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace yolo_grpc

