// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_grpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yolo_5fgrpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yolo_5fgrpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yolo_5fgrpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yolo_5fgrpc_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yolo_5fgrpc_2eproto;
namespace yolo_grpc {
class CamInfo;
class CamInfoDefaultTypeInternal;
extern CamInfoDefaultTypeInternal _CamInfo_default_instance_;
class Config;
class ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
class Detection;
class DetectionDefaultTypeInternal;
extern DetectionDefaultTypeInternal _Detection_default_instance_;
class DetectionLine;
class DetectionLineDefaultTypeInternal;
extern DetectionLineDefaultTypeInternal _DetectionLine_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace yolo_grpc
PROTOBUF_NAMESPACE_OPEN
template<> ::yolo_grpc::CamInfo* Arena::CreateMaybeMessage<::yolo_grpc::CamInfo>(Arena*);
template<> ::yolo_grpc::Config* Arena::CreateMaybeMessage<::yolo_grpc::Config>(Arena*);
template<> ::yolo_grpc::Detection* Arena::CreateMaybeMessage<::yolo_grpc::Detection>(Arena*);
template<> ::yolo_grpc::DetectionLine* Arena::CreateMaybeMessage<::yolo_grpc::DetectionLine>(Arena*);
template<> ::yolo_grpc::Point* Arena::CreateMaybeMessage<::yolo_grpc::Point>(Arena*);
template<> ::yolo_grpc::Response* Arena::CreateMaybeMessage<::yolo_grpc::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yolo_grpc {

// ===================================================================

class CamInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.CamInfo) */ {
 public:
  CamInfo();
  virtual ~CamInfo();

  CamInfo(const CamInfo& from);
  CamInfo(CamInfo&& from) noexcept
    : CamInfo() {
    *this = ::std::move(from);
  }

  inline CamInfo& operator=(const CamInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CamInfo& operator=(CamInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CamInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CamInfo* internal_default_instance() {
    return reinterpret_cast<const CamInfo*>(
               &_CamInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CamInfo& a, CamInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(CamInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CamInfo* New() const final {
    return CreateMaybeMessage<CamInfo>(nullptr);
  }

  CamInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CamInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CamInfo& from);
  void MergeFrom(const CamInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CamInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.CamInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrackFieldNumber = 5,
    kCamIdFieldNumber = 1,
    kImageFieldNumber = 3,
    kDetectionFieldNumber = 4,
    kTimestampFieldNumber = 2,
  };
  // repeated .yolo_grpc.Point track = 5;
  int track_size() const;
  private:
  int _internal_track_size() const;
  public:
  void clear_track();
  ::yolo_grpc::Point* mutable_track(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::Point >*
      mutable_track();
  private:
  const ::yolo_grpc::Point& _internal_track(int index) const;
  ::yolo_grpc::Point* _internal_add_track();
  public:
  const ::yolo_grpc::Point& track(int index) const;
  ::yolo_grpc::Point* add_track();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::Point >&
      track() const;

  // string cam_id = 1;
  void clear_cam_id();
  const std::string& cam_id() const;
  void set_cam_id(const std::string& value);
  void set_cam_id(std::string&& value);
  void set_cam_id(const char* value);
  void set_cam_id(const char* value, size_t size);
  std::string* mutable_cam_id();
  std::string* release_cam_id();
  void set_allocated_cam_id(std::string* cam_id);
  private:
  const std::string& _internal_cam_id() const;
  void _internal_set_cam_id(const std::string& value);
  std::string* _internal_mutable_cam_id();
  public:

  // bytes image = 3;
  void clear_image();
  const std::string& image() const;
  void set_image(const std::string& value);
  void set_image(std::string&& value);
  void set_image(const char* value);
  void set_image(const void* value, size_t size);
  std::string* mutable_image();
  std::string* release_image();
  void set_allocated_image(std::string* image);
  private:
  const std::string& _internal_image() const;
  void _internal_set_image(const std::string& value);
  std::string* _internal_mutable_image();
  public:

  // .yolo_grpc.Detection detection = 4;
  bool has_detection() const;
  private:
  bool _internal_has_detection() const;
  public:
  void clear_detection();
  const ::yolo_grpc::Detection& detection() const;
  ::yolo_grpc::Detection* release_detection();
  ::yolo_grpc::Detection* mutable_detection();
  void set_allocated_detection(::yolo_grpc::Detection* detection);
  private:
  const ::yolo_grpc::Detection& _internal_detection() const;
  ::yolo_grpc::Detection* _internal_mutable_detection();
  public:

  // int64 timestamp = 2;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.CamInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::Point > track_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cam_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_;
  ::yolo_grpc::Detection* detection_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class Detection :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.Detection) */ {
 public:
  Detection();
  virtual ~Detection();

  Detection(const Detection& from);
  Detection(Detection&& from) noexcept
    : Detection() {
    *this = ::std::move(from);
  }

  inline Detection& operator=(const Detection& from) {
    CopyFrom(from);
    return *this;
  }
  inline Detection& operator=(Detection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Detection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Detection* internal_default_instance() {
    return reinterpret_cast<const Detection*>(
               &_Detection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Detection& a, Detection& b) {
    a.Swap(&b);
  }
  inline void Swap(Detection* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Detection* New() const final {
    return CreateMaybeMessage<Detection>(nullptr);
  }

  Detection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Detection>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Detection& from);
  void MergeFrom(const Detection& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Detection* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.Detection";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXLeftFieldNumber = 1,
    kYTopFieldNumber = 2,
    kHeightFieldNumber = 3,
    kWidthFieldNumber = 4,
    kLineIdFieldNumber = 5,
  };
  // int32 x_left = 1;
  void clear_x_left();
  ::PROTOBUF_NAMESPACE_ID::int32 x_left() const;
  void set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x_left() const;
  void _internal_set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y_top = 2;
  void clear_y_top();
  ::PROTOBUF_NAMESPACE_ID::int32 y_top() const;
  void set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y_top() const;
  void _internal_set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 height = 3;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::int32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 width = 4;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::int32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 line_id = 5;
  void clear_line_id();
  ::PROTOBUF_NAMESPACE_ID::int32 line_id() const;
  void set_line_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_line_id() const;
  void _internal_set_line_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.Detection)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_left_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_top_;
  ::PROTOBUF_NAMESPACE_ID::int32 height_;
  ::PROTOBUF_NAMESPACE_ID::int32 width_;
  ::PROTOBUF_NAMESPACE_ID::int32 line_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class Point :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(nullptr);
  }

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.Point";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::int32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y = 2;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::int32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y() const;
  void _internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.Point)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class Response :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.Response";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
    kWarningFieldNumber = 2,
    kErrorFieldNumber = 3,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string warning = 2;
  void clear_warning();
  const std::string& warning() const;
  void set_warning(const std::string& value);
  void set_warning(std::string&& value);
  void set_warning(const char* value);
  void set_warning(const char* value, size_t size);
  std::string* mutable_warning();
  std::string* release_warning();
  void set_allocated_warning(std::string* warning);
  private:
  const std::string& _internal_warning() const;
  void _internal_set_warning(const std::string& value);
  std::string* _internal_mutable_warning();
  public:

  // string error = 3;
  void clear_error();
  const std::string& error() const;
  void set_error(const std::string& value);
  void set_error(std::string&& value);
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  std::string* mutable_error();
  std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.Response)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr warning_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class Config :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.Config) */ {
 public:
  Config();
  virtual ~Config();

  Config(const Config& from);
  Config(Config&& from) noexcept
    : Config() {
    *this = ::std::move(from);
  }

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Config& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Config* internal_default_instance() {
    return reinterpret_cast<const Config*>(
               &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Config& a, Config& b) {
    a.Swap(&b);
  }
  inline void Swap(Config* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Config* New() const final {
    return CreateMaybeMessage<Config>(nullptr);
  }

  Config* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Config>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Config& from);
  void MergeFrom(const Config& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Config* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.Config";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetectionLinesFieldNumber = 2,
    kUidFieldNumber = 1,
  };
  // repeated .yolo_grpc.DetectionLine detection_lines = 2;
  int detection_lines_size() const;
  private:
  int _internal_detection_lines_size() const;
  public:
  void clear_detection_lines();
  ::yolo_grpc::DetectionLine* mutable_detection_lines(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::DetectionLine >*
      mutable_detection_lines();
  private:
  const ::yolo_grpc::DetectionLine& _internal_detection_lines(int index) const;
  ::yolo_grpc::DetectionLine* _internal_add_detection_lines();
  public:
  const ::yolo_grpc::DetectionLine& detection_lines(int index) const;
  ::yolo_grpc::DetectionLine* add_detection_lines();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::DetectionLine >&
      detection_lines() const;

  // string uid = 1;
  void clear_uid();
  const std::string& uid() const;
  void set_uid(const std::string& value);
  void set_uid(std::string&& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  std::string* mutable_uid();
  std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  private:
  const std::string& _internal_uid() const;
  void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.Config)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::DetectionLine > detection_lines_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// -------------------------------------------------------------------

class DetectionLine :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yolo_grpc.DetectionLine) */ {
 public:
  DetectionLine();
  virtual ~DetectionLine();

  DetectionLine(const DetectionLine& from);
  DetectionLine(DetectionLine&& from) noexcept
    : DetectionLine() {
    *this = ::std::move(from);
  }

  inline DetectionLine& operator=(const DetectionLine& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectionLine& operator=(DetectionLine&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DetectionLine& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetectionLine* internal_default_instance() {
    return reinterpret_cast<const DetectionLine*>(
               &_DetectionLine_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(DetectionLine& a, DetectionLine& b) {
    a.Swap(&b);
  }
  inline void Swap(DetectionLine* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DetectionLine* New() const final {
    return CreateMaybeMessage<DetectionLine>(nullptr);
  }

  DetectionLine* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DetectionLine>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DetectionLine& from);
  void MergeFrom(const DetectionLine& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetectionLine* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yolo_grpc.DetectionLine";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_yolo_5fgrpc_2eproto);
    return ::descriptor_table_yolo_5fgrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBeginFieldNumber = 2,
    kEndFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // .yolo_grpc.Point begin = 2;
  bool has_begin() const;
  private:
  bool _internal_has_begin() const;
  public:
  void clear_begin();
  const ::yolo_grpc::Point& begin() const;
  ::yolo_grpc::Point* release_begin();
  ::yolo_grpc::Point* mutable_begin();
  void set_allocated_begin(::yolo_grpc::Point* begin);
  private:
  const ::yolo_grpc::Point& _internal_begin() const;
  ::yolo_grpc::Point* _internal_mutable_begin();
  public:

  // .yolo_grpc.Point end = 3;
  bool has_end() const;
  private:
  bool _internal_has_end() const;
  public:
  void clear_end();
  const ::yolo_grpc::Point& end() const;
  ::yolo_grpc::Point* release_end();
  ::yolo_grpc::Point* mutable_end();
  void set_allocated_end(::yolo_grpc::Point* end);
  private:
  const ::yolo_grpc::Point& _internal_end() const;
  ::yolo_grpc::Point* _internal_mutable_end();
  public:

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:yolo_grpc.DetectionLine)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::yolo_grpc::Point* begin_;
  ::yolo_grpc::Point* end_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yolo_5fgrpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CamInfo

// string cam_id = 1;
inline void CamInfo::clear_cam_id() {
  cam_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CamInfo::cam_id() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.cam_id)
  return _internal_cam_id();
}
inline void CamInfo::set_cam_id(const std::string& value) {
  _internal_set_cam_id(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.CamInfo.cam_id)
}
inline std::string* CamInfo::mutable_cam_id() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.cam_id)
  return _internal_mutable_cam_id();
}
inline const std::string& CamInfo::_internal_cam_id() const {
  return cam_id_.GetNoArena();
}
inline void CamInfo::_internal_set_cam_id(const std::string& value) {
  
  cam_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CamInfo::set_cam_id(std::string&& value) {
  
  cam_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.CamInfo.cam_id)
}
inline void CamInfo::set_cam_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cam_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.CamInfo.cam_id)
}
inline void CamInfo::set_cam_id(const char* value, size_t size) {
  
  cam_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.CamInfo.cam_id)
}
inline std::string* CamInfo::_internal_mutable_cam_id() {
  
  return cam_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CamInfo::release_cam_id() {
  // @@protoc_insertion_point(field_release:yolo_grpc.CamInfo.cam_id)
  
  return cam_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CamInfo::set_allocated_cam_id(std::string* cam_id) {
  if (cam_id != nullptr) {
    
  } else {
    
  }
  cam_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cam_id);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.CamInfo.cam_id)
}

// int64 timestamp = 2;
inline void CamInfo::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CamInfo::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CamInfo::timestamp() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.timestamp)
  return _internal_timestamp();
}
inline void CamInfo::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void CamInfo::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.CamInfo.timestamp)
}

// bytes image = 3;
inline void CamInfo::clear_image() {
  image_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CamInfo::image() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.image)
  return _internal_image();
}
inline void CamInfo::set_image(const std::string& value) {
  _internal_set_image(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.CamInfo.image)
}
inline std::string* CamInfo::mutable_image() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.image)
  return _internal_mutable_image();
}
inline const std::string& CamInfo::_internal_image() const {
  return image_.GetNoArena();
}
inline void CamInfo::_internal_set_image(const std::string& value) {
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CamInfo::set_image(std::string&& value) {
  
  image_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.CamInfo.image)
}
inline void CamInfo::set_image(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.CamInfo.image)
}
inline void CamInfo::set_image(const void* value, size_t size) {
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.CamInfo.image)
}
inline std::string* CamInfo::_internal_mutable_image() {
  
  return image_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CamInfo::release_image() {
  // @@protoc_insertion_point(field_release:yolo_grpc.CamInfo.image)
  
  return image_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CamInfo::set_allocated_image(std::string* image) {
  if (image != nullptr) {
    
  } else {
    
  }
  image_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.CamInfo.image)
}

// .yolo_grpc.Detection detection = 4;
inline bool CamInfo::_internal_has_detection() const {
  return this != internal_default_instance() && detection_ != nullptr;
}
inline bool CamInfo::has_detection() const {
  return _internal_has_detection();
}
inline void CamInfo::clear_detection() {
  if (GetArenaNoVirtual() == nullptr && detection_ != nullptr) {
    delete detection_;
  }
  detection_ = nullptr;
}
inline const ::yolo_grpc::Detection& CamInfo::_internal_detection() const {
  const ::yolo_grpc::Detection* p = detection_;
  return p != nullptr ? *p : *reinterpret_cast<const ::yolo_grpc::Detection*>(
      &::yolo_grpc::_Detection_default_instance_);
}
inline const ::yolo_grpc::Detection& CamInfo::detection() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.detection)
  return _internal_detection();
}
inline ::yolo_grpc::Detection* CamInfo::release_detection() {
  // @@protoc_insertion_point(field_release:yolo_grpc.CamInfo.detection)
  
  ::yolo_grpc::Detection* temp = detection_;
  detection_ = nullptr;
  return temp;
}
inline ::yolo_grpc::Detection* CamInfo::_internal_mutable_detection() {
  
  if (detection_ == nullptr) {
    auto* p = CreateMaybeMessage<::yolo_grpc::Detection>(GetArenaNoVirtual());
    detection_ = p;
  }
  return detection_;
}
inline ::yolo_grpc::Detection* CamInfo::mutable_detection() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.detection)
  return _internal_mutable_detection();
}
inline void CamInfo::set_allocated_detection(::yolo_grpc::Detection* detection) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete detection_;
  }
  if (detection) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      detection = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, detection, submessage_arena);
    }
    
  } else {
    
  }
  detection_ = detection;
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.CamInfo.detection)
}

// repeated .yolo_grpc.Point track = 5;
inline int CamInfo::_internal_track_size() const {
  return track_.size();
}
inline int CamInfo::track_size() const {
  return _internal_track_size();
}
inline void CamInfo::clear_track() {
  track_.Clear();
}
inline ::yolo_grpc::Point* CamInfo::mutable_track(int index) {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.CamInfo.track)
  return track_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::Point >*
CamInfo::mutable_track() {
  // @@protoc_insertion_point(field_mutable_list:yolo_grpc.CamInfo.track)
  return &track_;
}
inline const ::yolo_grpc::Point& CamInfo::_internal_track(int index) const {
  return track_.Get(index);
}
inline const ::yolo_grpc::Point& CamInfo::track(int index) const {
  // @@protoc_insertion_point(field_get:yolo_grpc.CamInfo.track)
  return _internal_track(index);
}
inline ::yolo_grpc::Point* CamInfo::_internal_add_track() {
  return track_.Add();
}
inline ::yolo_grpc::Point* CamInfo::add_track() {
  // @@protoc_insertion_point(field_add:yolo_grpc.CamInfo.track)
  return _internal_add_track();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::Point >&
CamInfo::track() const {
  // @@protoc_insertion_point(field_list:yolo_grpc.CamInfo.track)
  return track_;
}

// -------------------------------------------------------------------

// Detection

// int32 x_left = 1;
inline void Detection::clear_x_left() {
  x_left_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_x_left() const {
  return x_left_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::x_left() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.x_left)
  return _internal_x_left();
}
inline void Detection::_internal_set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_left_ = value;
}
inline void Detection::set_x_left(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x_left(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.x_left)
}

// int32 y_top = 2;
inline void Detection::clear_y_top() {
  y_top_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_y_top() const {
  return y_top_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::y_top() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.y_top)
  return _internal_y_top();
}
inline void Detection::_internal_set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_top_ = value;
}
inline void Detection::set_y_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y_top(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.y_top)
}

// int32 height = 3;
inline void Detection::clear_height() {
  height_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::height() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.height)
  return _internal_height();
}
inline void Detection::_internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  height_ = value;
}
inline void Detection::set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.height)
}

// int32 width = 4;
inline void Detection::clear_width() {
  width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::width() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.width)
  return _internal_width();
}
inline void Detection::_internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  width_ = value;
}
inline void Detection::set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.width)
}

// int32 line_id = 5;
inline void Detection::clear_line_id() {
  line_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::_internal_line_id() const {
  return line_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Detection::line_id() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Detection.line_id)
  return _internal_line_id();
}
inline void Detection::_internal_set_line_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  line_id_ = value;
}
inline void Detection::set_line_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_line_id(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Detection.line_id)
}

// -------------------------------------------------------------------

// Point

// int32 x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Point::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Point::x() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_ = value;
}
inline void Point::set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Point.x)
}

// int32 y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Point::_internal_y() const {
  return y_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Point::y() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_ = value;
}
inline void Point::set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Point.y)
}

// -------------------------------------------------------------------

// Response

// string message = 1;
inline void Response::clear_message() {
  message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::message() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Response.message)
  return _internal_message();
}
inline void Response::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Response.message)
}
inline std::string* Response::mutable_message() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Response.message)
  return _internal_mutable_message();
}
inline const std::string& Response::_internal_message() const {
  return message_.GetNoArena();
}
inline void Response::_internal_set_message(const std::string& value) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response::set_message(std::string&& value) {
  
  message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Response.message)
}
inline void Response::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Response.message)
}
inline void Response::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Response.message)
}
inline std::string* Response::_internal_mutable_message() {
  
  return message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_message() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Response.message)
  
  return message_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Response.message)
}

// string warning = 2;
inline void Response::clear_warning() {
  warning_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::warning() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Response.warning)
  return _internal_warning();
}
inline void Response::set_warning(const std::string& value) {
  _internal_set_warning(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Response.warning)
}
inline std::string* Response::mutable_warning() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Response.warning)
  return _internal_mutable_warning();
}
inline const std::string& Response::_internal_warning() const {
  return warning_.GetNoArena();
}
inline void Response::_internal_set_warning(const std::string& value) {
  
  warning_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response::set_warning(std::string&& value) {
  
  warning_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Response.warning)
}
inline void Response::set_warning(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  warning_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Response.warning)
}
inline void Response::set_warning(const char* value, size_t size) {
  
  warning_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Response.warning)
}
inline std::string* Response::_internal_mutable_warning() {
  
  return warning_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_warning() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Response.warning)
  
  return warning_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_warning(std::string* warning) {
  if (warning != nullptr) {
    
  } else {
    
  }
  warning_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), warning);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Response.warning)
}

// string error = 3;
inline void Response::clear_error() {
  error_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::error() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Response.error)
  return _internal_error();
}
inline void Response::set_error(const std::string& value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Response.error)
}
inline std::string* Response::mutable_error() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Response.error)
  return _internal_mutable_error();
}
inline const std::string& Response::_internal_error() const {
  return error_.GetNoArena();
}
inline void Response::_internal_set_error(const std::string& value) {
  
  error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response::set_error(std::string&& value) {
  
  error_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Response.error)
}
inline void Response::set_error(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Response.error)
}
inline void Response::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Response.error)
}
inline std::string* Response::_internal_mutable_error() {
  
  return error_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_error() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Response.error)
  
  return error_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Response.error)
}

// -------------------------------------------------------------------

// Config

// string uid = 1;
inline void Config::clear_uid() {
  uid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Config::uid() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Config.uid)
  return _internal_uid();
}
inline void Config::set_uid(const std::string& value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.Config.uid)
}
inline std::string* Config::mutable_uid() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Config.uid)
  return _internal_mutable_uid();
}
inline const std::string& Config::_internal_uid() const {
  return uid_.GetNoArena();
}
inline void Config::_internal_set_uid(const std::string& value) {
  
  uid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Config::set_uid(std::string&& value) {
  
  uid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yolo_grpc.Config.uid)
}
inline void Config::set_uid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yolo_grpc.Config.uid)
}
inline void Config::set_uid(const char* value, size_t size) {
  
  uid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yolo_grpc.Config.uid)
}
inline std::string* Config::_internal_mutable_uid() {
  
  return uid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Config::release_uid() {
  // @@protoc_insertion_point(field_release:yolo_grpc.Config.uid)
  
  return uid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Config::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uid);
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.Config.uid)
}

// repeated .yolo_grpc.DetectionLine detection_lines = 2;
inline int Config::_internal_detection_lines_size() const {
  return detection_lines_.size();
}
inline int Config::detection_lines_size() const {
  return _internal_detection_lines_size();
}
inline void Config::clear_detection_lines() {
  detection_lines_.Clear();
}
inline ::yolo_grpc::DetectionLine* Config::mutable_detection_lines(int index) {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.Config.detection_lines)
  return detection_lines_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::DetectionLine >*
Config::mutable_detection_lines() {
  // @@protoc_insertion_point(field_mutable_list:yolo_grpc.Config.detection_lines)
  return &detection_lines_;
}
inline const ::yolo_grpc::DetectionLine& Config::_internal_detection_lines(int index) const {
  return detection_lines_.Get(index);
}
inline const ::yolo_grpc::DetectionLine& Config::detection_lines(int index) const {
  // @@protoc_insertion_point(field_get:yolo_grpc.Config.detection_lines)
  return _internal_detection_lines(index);
}
inline ::yolo_grpc::DetectionLine* Config::_internal_add_detection_lines() {
  return detection_lines_.Add();
}
inline ::yolo_grpc::DetectionLine* Config::add_detection_lines() {
  // @@protoc_insertion_point(field_add:yolo_grpc.Config.detection_lines)
  return _internal_add_detection_lines();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yolo_grpc::DetectionLine >&
Config::detection_lines() const {
  // @@protoc_insertion_point(field_list:yolo_grpc.Config.detection_lines)
  return detection_lines_;
}

// -------------------------------------------------------------------

// DetectionLine

// int32 id = 1;
inline void DetectionLine::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DetectionLine::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DetectionLine::id() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.DetectionLine.id)
  return _internal_id();
}
inline void DetectionLine::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void DetectionLine::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:yolo_grpc.DetectionLine.id)
}

// .yolo_grpc.Point begin = 2;
inline bool DetectionLine::_internal_has_begin() const {
  return this != internal_default_instance() && begin_ != nullptr;
}
inline bool DetectionLine::has_begin() const {
  return _internal_has_begin();
}
inline void DetectionLine::clear_begin() {
  if (GetArenaNoVirtual() == nullptr && begin_ != nullptr) {
    delete begin_;
  }
  begin_ = nullptr;
}
inline const ::yolo_grpc::Point& DetectionLine::_internal_begin() const {
  const ::yolo_grpc::Point* p = begin_;
  return p != nullptr ? *p : *reinterpret_cast<const ::yolo_grpc::Point*>(
      &::yolo_grpc::_Point_default_instance_);
}
inline const ::yolo_grpc::Point& DetectionLine::begin() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.DetectionLine.begin)
  return _internal_begin();
}
inline ::yolo_grpc::Point* DetectionLine::release_begin() {
  // @@protoc_insertion_point(field_release:yolo_grpc.DetectionLine.begin)
  
  ::yolo_grpc::Point* temp = begin_;
  begin_ = nullptr;
  return temp;
}
inline ::yolo_grpc::Point* DetectionLine::_internal_mutable_begin() {
  
  if (begin_ == nullptr) {
    auto* p = CreateMaybeMessage<::yolo_grpc::Point>(GetArenaNoVirtual());
    begin_ = p;
  }
  return begin_;
}
inline ::yolo_grpc::Point* DetectionLine::mutable_begin() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.DetectionLine.begin)
  return _internal_mutable_begin();
}
inline void DetectionLine::set_allocated_begin(::yolo_grpc::Point* begin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete begin_;
  }
  if (begin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      begin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, begin, submessage_arena);
    }
    
  } else {
    
  }
  begin_ = begin;
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.DetectionLine.begin)
}

// .yolo_grpc.Point end = 3;
inline bool DetectionLine::_internal_has_end() const {
  return this != internal_default_instance() && end_ != nullptr;
}
inline bool DetectionLine::has_end() const {
  return _internal_has_end();
}
inline void DetectionLine::clear_end() {
  if (GetArenaNoVirtual() == nullptr && end_ != nullptr) {
    delete end_;
  }
  end_ = nullptr;
}
inline const ::yolo_grpc::Point& DetectionLine::_internal_end() const {
  const ::yolo_grpc::Point* p = end_;
  return p != nullptr ? *p : *reinterpret_cast<const ::yolo_grpc::Point*>(
      &::yolo_grpc::_Point_default_instance_);
}
inline const ::yolo_grpc::Point& DetectionLine::end() const {
  // @@protoc_insertion_point(field_get:yolo_grpc.DetectionLine.end)
  return _internal_end();
}
inline ::yolo_grpc::Point* DetectionLine::release_end() {
  // @@protoc_insertion_point(field_release:yolo_grpc.DetectionLine.end)
  
  ::yolo_grpc::Point* temp = end_;
  end_ = nullptr;
  return temp;
}
inline ::yolo_grpc::Point* DetectionLine::_internal_mutable_end() {
  
  if (end_ == nullptr) {
    auto* p = CreateMaybeMessage<::yolo_grpc::Point>(GetArenaNoVirtual());
    end_ = p;
  }
  return end_;
}
inline ::yolo_grpc::Point* DetectionLine::mutable_end() {
  // @@protoc_insertion_point(field_mutable:yolo_grpc.DetectionLine.end)
  return _internal_mutable_end();
}
inline void DetectionLine::set_allocated_end(::yolo_grpc::Point* end) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete end_;
  }
  if (end) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      end = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, end, submessage_arena);
    }
    
  } else {
    
  }
  end_ = end;
  // @@protoc_insertion_point(field_set_allocated:yolo_grpc.DetectionLine.end)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace yolo_grpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yolo_5fgrpc_2eproto
